[project]
name = "bidiagent-on-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "bedrock-agentcore>=1.1.1",
    "strands-agents-tools>=0.2.17",
    "strands-agents[bidi,bidi-all]>=1.19.0",
]
